apiVersion: v1
kind: Service
metadata:
  name: node-express-web-sample-01-docker
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    run: node-express-web-sample-01-docker
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: node-express-web-sample-01-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-web-sample-01-docker
spec:
  selector:
    matchLabels:
      run: sb-web-sample-01-dockernode-express-web-sample-01-docker
  replicas: 1
  template:
    metadata:
      labels:
        run: node-express-web-sample-01-docker
    spec:
      containers:
      - name: node-express-web-sample-01-docker
        image: easonlai/node-express-web-sample-01-docker
        ports:
        - containerPort: 3000